apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ycn9d1q1b-go
  janus-idp.io/tekton: ycn9d1q1b-go
  backstage.io/kubernetes-id: ycn9d1q1b-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: ycn9d1q1b-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
