apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ycn9d1q1b-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ycn9d1q1b-go 
  name: ycn9d1q1b-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: ycn9d1q1b-go 
